from embedding_models import MFCC, Hubert, Wav2Vec2, DVector, XVector, Miipher, Voicefixer, Whisper, Wav2Vec2WER
from kaldi_wer import get_kaldi_wasserstein

if __name__ == "__main__":
    print("Kaldi WER")
    print("Parler:", get_kaldi_wasserstein("parler"))
    print("Hifigan:", get_kaldi_wasserstein("hifigan"))
    print("Xtts:", get_kaldi_wasserstein("xtts"))

    mfcc = MFCC()
    print("MFCC")
    print("Reference dev:", mfcc.get_frechet("reference.dev"))
    print("Parler:", mfcc.get_frechet("parler"))
    print("Hifigan:", mfcc.get_frechet("hifigan"))
    print("Xtts:", mfcc.get_frechet("xtts"))

    hubert = Hubert()
    print("Hubert")
    print("Reference dev:", hubert.get_frechet("reference.dev"))
    print("Parler:", hubert.get_frechet("parler"))
    print("Hifigan:", hubert.get_frechet("hifigan"))
    print("Xtts:", hubert.get_frechet("xtts"))

    wav2vec2 = Wav2Vec2()
    print("Wav2Vec2")
    print("Reference dev:", wav2vec2.get_frechet("reference.dev"))
    print("Parler:", wav2vec2.get_frechet("parler"))
    print("Hifigan:", wav2vec2.get_frechet("hifigan"))
    print("Xtts:", wav2vec2.get_frechet("xtts"))

    dvector = DVector()
    print("DVector")
    print("Reference dev:", dvector.get_frechet("reference.dev"))
    print("Parler:", dvector.get_frechet("parler"))
    print("Hifigan:", dvector.get_frechet("hifigan"))
    print("Xtts:", dvector.get_frechet("xtts"))

    xvector = XVector()
    print("XVector")
    print("Reference dev:", xvector.get_frechet("reference.dev"))
    print("Parler:", xvector.get_frechet("parler"))
    print("Hifigan:", xvector.get_frechet("hifigan"))
    print("Xtts:", xvector.get_frechet("xtts"))

    miipher = Miipher()
    print("Miipher")
    print("Reference dev:", miipher.get_frechet("reference.dev"))
    print("Parler:", miipher.get_frechet("parler"))
    print("Hifigan:", miipher.get_frechet("hifigan"))
    print("Xtts:", miipher.get_frechet("xtts"))

    voicefixer = Voicefixer("cpu")
    print("Voicefixer")
    print("Reference dev:", voicefixer.get_frechet("reference.dev"))
    print("Parler:", voicefixer.get_frechet("parler"))
    print("Hifigan:", voicefixer.get_frechet("hifigan"))
    print("Xtts:", voicefixer.get_frechet("xtts"))

    whisper = Whisper()
    print("Whisper")
    print("Reference dev:", whisper.get_wasserstein("reference.dev"))
    print("Parler:", whisper.get_wasserstein("parler"))
    print("Hifigan:", whisper.get_wasserstein("hifigan"))
    print("Xtts:", whisper.get_wasserstein("xtts"))

    wav2vec2_wer = Wav2Vec2WER()
    print("Wav2Vec2WER")
    print("Reference dev:", wav2vec2_wer.get_wasserstein("reference.dev"))
    print("Parler:", wav2vec2_wer.get_wasserstein("parler"))
    print("Hifigan:", wav2vec2_wer.get_wasserstein("hifigan"))
    print("Xtts:", wav2vec2_wer.get_wasserstein("xtts"))