from embedding_models import (
    MFCC,
    Hubert, 
    Wav2Vec2, 
    DVector,
    DVectorIntra, 
    XVector, 
    XVectorIntra,
    Miipher, 
    Voicefixer, 
    Whisper, 
    Wav2Vec2WER, 
    ProsodyMPM
)
from kaldi_wer import get_kaldi_wasserstein
from hubert_units import HubertUnitCounter
from pathlib import Path

Path("cache").mkdir(exist_ok=True)
Path("results").mkdir(exist_ok=True)

if __name__ == "__main__":
    mfcc = MFCC()
    print("MFCC")
    print("Reference dev:", mfcc.get_frechet("reference.dev"))
    print("Parler:", mfcc.get_frechet("parler"))
    print("Hifigan:", mfcc.get_frechet("hifigan"))
    print("Xtts:", mfcc.get_frechet("xtts"))
    print("LJSpeech:", mfcc.get_frechet("ljspeech"))
    print("Tacotron2:", mfcc.get_frechet("tacotron"))

    hubert_units = HubertUnitCounter()
    print("Hubert Units")
    print("Reference dev:", hubert_units.get_wasserstein_distances("reference.dev"))
    print("Parler:", hubert_units.get_wasserstein_distances("parler"))
    print("Hifigan:", hubert_units.get_wasserstein_distances("hifigan"))
    print("Xtts:", hubert_units.get_wasserstein_distances("xtts"))
    print("LJSpeech:", hubert_units.get_wasserstein_distances("ljspeech"))
    print("Tacotron2:", hubert_units.get_wasserstein_distances("lj_tacotron2"))

    prosody = ProsodyMPM()
    print("Prosody")
    print("Reference dev:", prosody.get_frechet("reference.dev"))
    print("Parler:", prosody.get_frechet("parler"))
    print("Hifigan:", prosody.get_frechet("hifigan"))
    print("Xtts:", prosody.get_frechet("xtts"))
    print("LJSpeech:", prosody.get_frechet("ljspeech"))
    print("Tacotron2:", prosody.get_frechet("tacotron"))

    print("Kaldi WER")
    print("Reference dev:", get_kaldi_wasserstein("reference.dev"))
    print("Parler:", get_kaldi_wasserstein("parler"))
    print("Hifigan:", get_kaldi_wasserstein("hifigan"))
    print("Xtts:", get_kaldi_wasserstein("xtts"))
    print("LJSpeech:", get_kaldi_wasserstein("ljspeech"))
    print("Tacotron2:", get_kaldi_wasserstein("tacotron"))

    mfcc = MFCC()
    print("MFCC")
    print("Reference dev:", mfcc.get_frechet("reference.dev"))
    print("Parler:", mfcc.get_frechet("parler"))
    print("Hifigan:", mfcc.get_frechet("hifigan"))
    print("Xtts:", mfcc.get_frechet("xtts"))
    print("LJSpeech:", mfcc.get_frechet("ljspeech"))
    print("Tacotron2:", mfcc.get_frechet("tacotron"))

    hubert = Hubert()
    print("Hubert")
    print("Reference dev:", hubert.get_frechet("reference.dev"))
    print("Parler:", hubert.get_frechet("parler"))
    print("Hifigan:", hubert.get_frechet("hifigan"))
    print("Xtts:", hubert.get_frechet("xtts"))
    print("LJSpeech:", hubert.get_frechet("ljspeech"))
    print("Tacotron2:", hubert.get_frechet("tacotron"))

    wav2vec2 = Wav2Vec2()
    print("Wav2Vec2")
    print("Reference dev:", wav2vec2.get_frechet("reference.dev"))
    print("Parler:", wav2vec2.get_frechet("parler"))
    print("Hifigan:", wav2vec2.get_frechet("hifigan"))
    print("Xtts:", wav2vec2.get_frechet("xtts"))
    print("LJSpeech:", wav2vec2.get_frechet("ljspeech"))
    print("Tacotron2:", wav2vec2.get_frechet("tacotron"))

    dvector = DVector()
    print("DVector")
    print("Reference dev:", dvector.get_frechet("reference.dev"))
    print("Parler:", dvector.get_frechet("parler"))
    print("Hifigan:", dvector.get_frechet("hifigan"))
    print("Xtts:", dvector.get_frechet("xtts"))
    print("LJSpeech:", dvector.get_frechet("ljspeech"))
    print("Tacotron2:", dvector.get_frechet("tacotron"))

    print("DVector (Intra)")
    dvector = DVectorIntra("reference.dev")
    print("Reference dev:", dvector.get_frechet("reference.dev"))
    dvector = DVectorIntra("parler")
    print("Parler:", dvector.get_frechet("parler"))
    dvector = DVectorIntra("hifigan")
    print("Hifigan:", dvector.get_frechet("hifigan"))
    dvector = DVectorIntra("xtts")
    print("Xtts:", dvector.get_frechet("xtts"))
    dvector = DVectorIntra("ljspeech")
    print("LJSpeech:", dvector.get_frechet("ljspeech"))
    dvector = DVectorIntra("tacotron")
    print("Tacotron2:", dvector.get_frechet("tacotron"))

    xvector = XVector()
    print("XVector")
    print("Reference dev:", xvector.get_frechet("reference.dev"))
    print("Parler:", xvector.get_frechet("parler"))
    print("Hifigan:", xvector.get_frechet("hifigan"))
    print("Xtts:", xvector.get_frechet("xtts"))
    print("LJSpeech:", xvector.get_frechet("ljspeech"))
    print("Tacotron2:", xvector.get_frechet("tacotron"))

    print("XVector (Intra)")
    xvector = XVectorIntra("reference.dev")
    print("Reference dev:", xvector.get_frechet("reference.dev"))
    xvector = XVectorIntra("parler")
    print("Parler:", xvector.get_frechet("parler"))
    xvector = XVectorIntra("hifigan")
    print("Hifigan:", xvector.get_frechet("hifigan"))
    xvector = XVectorIntra("xtts")
    print("Xtts:", xvector.get_frechet("xtts"))
    xvector = XVectorIntra("ljspeech")
    print("LJSpeech:", xvector.get_frechet("ljspeech"))
    xvector = XVectorIntra("tacotron")
    print("Tacotron2:", xvector.get_frechet("tacotron"))

    miipher = Miipher(device="cpu", audio_features="hubert", audio_features_device="cuda")
    print("Miipher (hubert)")
    print("Reference dev:", miipher.get_frechet("reference.dev"))
    print("Parler:", miipher.get_frechet("parler"))
    print("Hifigan:", miipher.get_frechet("hifigan"))
    print("Xtts:", miipher.get_frechet("xtts"))
    print("LJSpeech:", miipher.get_frechet("ljspeech"))
    print("Tacotron2:", miipher.get_frechet("tacotron"))

    miipher = Miipher(device="cpu", audio_features="mfcc")
    print("Miipher (mfcc)")
    print("Reference dev:", miipher.get_frechet("reference.dev"))
    print("Parler:", miipher.get_frechet("parler"))
    print("Hifigan:", miipher.get_frechet("hifigan"))
    print("Xtts:", miipher.get_frechet("xtts"))
    print("LJSpeech:", miipher.get_frechet("ljspeech"))
    print("Tacotron2:", miipher.get_frechet("tacotron"))

    voicefixer = Voicefixer("cpu", audio_features="hubert", audio_features_device="cuda")
    print("Voicefixer (hubert)")
    print("Reference dev:", voicefixer.get_frechet("reference.dev"))
    print("Parler:", voicefixer.get_frechet("parler"))
    print("Hifigan:", voicefixer.get_frechet("hifigan"))
    print("Xtts:", voicefixer.get_frechet("xtts"))
    print("LJSpeech:", voicefixer.get_frechet("ljspeech"))
    print("Tacotron2:", voicefixer.get_frechet("tacotron"))

    voicefixer = Voicefixer("cpu", audio_features="mfcc")
    print("Voicefixer (mfcc)")
    print("Reference dev:", voicefixer.get_frechet("reference.dev"))
    print("Parler:", voicefixer.get_frechet("parler"))
    print("Hifigan:", voicefixer.get_frechet("hifigan"))
    print("Xtts:", voicefixer.get_frechet("xtts"))
    print("LJSpeech:", voicefixer.get_frechet("ljspeech"))
    print("Tacotron2:", voicefixer.get_frechet("tacotron"))

    whisper = Whisper()
    print("Whisper")
    print("Reference dev:", whisper.get_wasserstein("reference.dev"))
    print("Parler:", whisper.get_wasserstein("parler"))
    print("Hifigan:", whisper.get_wasserstein("hifigan"))
    print("Xtts:", whisper.get_wasserstein("xtts"))
    print("LJSpeech:", whisper.get_wasserstein("ljspeech"))
    print("Tacotron2:", whisper.get_wasserstein("tacotron"))

    wav2vec2_wer = Wav2Vec2WER()
    print("Wav2Vec2WER")
    print("Reference dev:", wav2vec2_wer.get_wasserstein("reference.dev"))
    print("Parler:", wav2vec2_wer.get_wasserstein("parler"))
    print("Hifigan:", wav2vec2_wer.get_wasserstein("hifigan"))
    print("Xtts:", wav2vec2_wer.get_wasserstein("xtts"))
    print("LJSpeech:", wav2vec2_wer.get_wasserstein("ljspeech"))
    print("Tacotron2:", wav2vec2_wer.get_wasserstein("tacotron"))